spring:
  profiles:
    active: development,default

aws:
  ftp:
    host: s-64885e165c8148c89.server.transfer.us-east-2.amazonaws.com
    port: 22
    user: lbisaria
    certPath:  /Users/love.bisaria/.ssh/amazon_ftp
    certPass: lbisaria
    remotePath:  /leo-dev-bucket